server:
  port: 8080
spring:
  thymeleaf:
    cache: false

#配置数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: db_user
    password: kybb123456
    url: jdbc:mysql://10.1.80.166:3306/test_tsc_b?useUnicode=true&characterEncoding=UTF8&useSSL=false

#配置sql映射
mybatis:
  type-aliases-package: com.chapter6
  mapper-locations:
    - mybatis/mapper/*
#配置sql的打印
logging:
  level:
    com.example.demo.dao : debug


